version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
      - "3001:3000"
    networks:
      - moyu_net
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  moyu_net:
    driver: bridge

volumes:
  mongo_data:
  redis_data: 